# Generated by Django 4.2.11 on 2025-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartridges_departments_printers_alter_staff_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='date_of_last_location',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
