# Generated by Django 5.2.3 on 2025-07-08 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cartridge_models_alter_cartridges_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridges_printers',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='cartridges_printers',
            name='cartridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cartridges_Printers_cartridge_model_id', to='main.cartridge_models'),
        ),
    ]
