# Generated by Django 5.2.3 on 2025-07-22 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cartridges_printers_cartridge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departments'),
        ),
    ]
