# Generated by Django 5.2.3 on 2025-07-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_staff_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department_id',
            new_name='department',
        ),
    ]
