# Generated by Django 5.2.3 on 2025-08-19 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_department_id_staff_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartridges',
            new_name='Cartridge',
        ),
        migrations.RenameModel(
            old_name='Cartridge_Models',
            new_name='CartridgeModel',
        ),
        migrations.RenameModel(
            old_name='Cartridges_History',
            new_name='CartridgesHistory',
        ),
        migrations.RenameModel(
            old_name='Cartridges_Printers',
            new_name='CartridgesPrinter',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
